"""Add game families

Revision ID: 788465408584
Revises: ac8e268006a5
Create Date: 2026-04-14 20:02:16.072320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788465408584'
down_revision: Union[str, Sequence[str], None] = 'ac8e268006a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'game_families' not in tables:
        op.create_table('game_families',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('cover_path', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_game_families_id'), 'game_families', ['id'], unique=False)
        op.create_index(op.f('ix_game_families_name'), 'game_families', ['name'], unique=True)
    
    columns = [c['name'] for c in inspector.get_columns('game_meta')]
    if 'family_id' not in columns:
        op.add_column('game_meta', sa.Column('family_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'game_meta', 'game_families', ['family_id'], ['id'])
    
    if 'zip_label' in columns:
        op.drop_column('game_meta', 'zip_label')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('game_meta')]

    if 'zip_label' not in columns:
        op.add_column('game_meta', sa.Column('zip_label', sa.VARCHAR(), nullable=True))
    
    if 'family_id' in columns:
        # Note: drop_constraint is complex on SQLite, but op.drop_column usually works for FKs too
        op.drop_column('game_meta', 'family_id')
    
    tables = inspector.get_table_names()
    if 'game_families' in tables:
        op.drop_index(op.f('ix_game_families_name'), table_name='game_families')
        op.drop_index(op.f('ix_game_families_id'), table_name='game_families')
        op.drop_table('game_families')
    # ### end Alembic commands ###
